name: Docker Build and Push

on:
  push:
    branches:
      - master

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  IMAGE_NAME: nodejs
  TAG: latest
  AWS_INSTANCE_IP: ${{ secrets.HOSTNAME }}
  AWS_INSTANCE_KEY: ${{ secrets.PUBLIC_KEY }}
  AWS_INSTANCE_USERNAME: ${{ secrets.USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          
      - name: Connect to AWS instance and run command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOSTNAME }}
          username: ${{ env.USERNAME }}
          key: ${{ env.PUBLIC_KEY }}
          port: 22
          script: |
             docker pull ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}     
