name: Build and Push Docker Image

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: nodejs
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: 'Login to GitHub Container Registry'
        run: |
          echo $TOKEN | docker login ghcr.io -u hackcoderr --password-stdin
          
      
      - name: Tag image as latest
        run: |
          docker tag ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
          docker push ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
