name: Nodejs Project Demo CI/CD

on:
  push:
    branches:
      - master

env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  IMAGE_NAME: nodejs

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the commit SHA
        id: commit_sha
        run: echo "::set-output name=SHA::$(git rev-parse --short HEAD)"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.commit_sha.outputs.SHA }}
          
          
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.PUBLIC_KEY }}
            HOSTNAME: ${{ secrets.HOSTNAME }}
            USER_NAME: ${{ secrets.USERNAME }}
            IMAGE_TAG: ${{ github.sha }}
            
        run: |
          set -x
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '          
            cd nodejs
            docker-compose pull
            IMAGE_TAG=$IMAGE_TAG docker-compose up -d 
          '
